databases:
  - name: hms_db
    databaseName: hms
    user: hms_user
    plan: free

services:
  - type: web
    name: hostel_system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Hostel_System.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hms_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.12.0
